name: Wings Guild API CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      # Add other steps like testing here

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pm2 stop all
            rm -rf wings-guild-api
            git clone -b main https://github.com/FullSol/wings-guild-api.git
            cd wings-guild-api
            npm install
            cd bin
            pm2 start www
            pm2 save
